# Generated by Django 6.1.1 on 2026-10-03 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('cafe', 'Café da manhã'), ('almoco', 'Almoço'), ('lanche', 'Lanche'), ('jantar', 'Jantar'), ('outro', 'Outro')], max_length=10)),
                ('descricao', models.TextField()),
                ('calorias', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refeição',
                'verbose_name_plural': 'refeições',
                'ordering': ['-data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('concluida', models.BooleanField(default=False)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.atividade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('atividade', 'data'), name='uma_marcacao_por_dia')],
            },
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'data'), name='um_peso_por_dia')],
            },
        ),
    ]
